template-file-path: src/ec2-codedeploy-launchtemplate.yml

parameters:
    InstanceType: t3.micro
    LatestAmiId: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64

tags:
    environment: 'dev'
    project: 'ec2-codedeploy'